# -*- coding: utf-8 -*-
"""issue #4 凭证降级：统一更新 5 语言包文案（app.json envBanner/envErrors + settings.json credentials）"""
import json, os

BASE = os.path.join(os.path.dirname(__file__), '..', 'webview', 'src', 'i18n', 'locales')

# app.json / settings.json 的新文案（key 结构：app 前缀省略）
APP = {
    'zh': {
        'advisoryTitle': '运行环境提示（对话功能不受影响）',
        'credsDegraded': '未找到可注入的 API Key 凭证（账号登录为加密存储）：对话将使用 ZCode 客户端自身登录态；用量查询等辅助功能不可用',
        'credsMissing': '配置文件不存在：{{arg}}（对话不受影响，将使用 ZCode 客户端登录态）',
        'credsInvalid': '配置文件无可用明文凭证：{{arg}}（账号登录凭证为加密存储；对话不受影响，将使用 ZCode 客户端登录态）',
        'hint': '凭证由 ZCode 客户端登录生成（~/.zcode/v2/config.json）。账号（oauth）登录的凭证为加密存储，此时对话自动改用 ZCode 客户端登录态，用量查询等辅助功能不可用',
        'degraded': '无明文凭证 · 走客户端登录态',
    },
    'zh-TW': {
        'advisoryTitle': '執行環境提示（對話功能不受影響）',
        'credsDegraded': '未找到可注入的 API Key 憑證（帳號登入為加密儲存）：對話將使用 ZCode 用戶端自身登入態；用量查詢等輔助功能不可用',
        'credsMissing': '設定檔不存在：{{arg}}（對話不受影響，將使用 ZCode 用戶端登入態）',
        'credsInvalid': '設定檔無可用明文憑證：{{arg}}（帳號登入憑證為加密儲存；對話不受影響，將使用 ZCode 用戶端登入態）',
        'hint': '憑證由 ZCode 用戶端登入產生（~/.zcode/v2/config.json）。帳號（oauth）登入的憑證為加密儲存，此時對話自動改用 ZCode 用戶端登入態，用量查詢等輔助功能不可用',
        'degraded': '無明文憑證 · 走用戶端登入態',
    },
    'en': {
        'advisoryTitle': 'Runtime notice (chat unaffected)',
        'credsDegraded': 'No injectable API key credential found (account login stores it encrypted): chat will use the ZCode client\'s own login state; auxiliary features such as usage stats are unavailable',
        'credsMissing': 'config file does not exist: {{arg}} (chat unaffected — the ZCode client login state will be used)',
        'credsInvalid': 'no usable plaintext credential in config file: {{arg}} (account-login credentials are stored encrypted; chat unaffected — the ZCode client login state will be used)',
        'hint': 'Credentials are generated by logging in with the ZCode client (~/.zcode/v2/config.json). With account (OAuth) login the credential is stored encrypted — chat then uses the ZCode client\'s own login state, and auxiliary features such as usage stats are unavailable',
        'degraded': 'No plaintext key · client login',
    },
    'ja': {
        'advisoryTitle': '実行環境の通知（チャットへの影響なし）',
        'credsDegraded': '注入可能な API キーが見つかりません（アカウントログインでは暗号化して保存）：チャットは ZCode クライアント自身のログイン状態を使用します。使用量照会などの補助機能は利用できません',
        'credsMissing': '設定ファイルが存在しません：{{arg}}（チャットへの影響なし。ZCode クライアントのログイン状態を使用します）',
        'credsInvalid': '設定ファイルに利用可能な平文資格情報がありません：{{arg}}（アカウントログインの資格情報は暗号化保存。チャットへの影響なし。ZCode クライアントのログイン状態を使用します）',
        'hint': '認証情報は ZCode クライアントのログインで生成されます（~/.zcode/v2/config.json）。アカウント（OAuth）ログインでは暗号化して保存され、その場合チャットは ZCode クライアント自身のログイン状態を使用します。使用量照会などの補助機能は利用できません',
        'degraded': '平文キーなし · クライアントログイン',
    },
    'ko': {
        'advisoryTitle': '런타임 알림(채팅 영향 없음)',
        'credsDegraded': '주입 가능한 API 키 자격 증명을 찾을 수 없습니다(계정 로그인 시 암호화 저장): 채팅은 ZCode 클라이언트 자체 로그인 상태를 사용하며 사용량 조회 등 보조 기능은 사용할 수 없습니다',
        'credsMissing': '구성 파일이 없습니다: {{arg}}(채팅 영향 없음, ZCode 클라이언트 로그인 상태 사용)',
        'credsInvalid': '구성 파일에 사용 가능한 평문 자격 증명이 없습니다: {{arg}}(계정 로그인 자격 증명은 암호화 저장, 채팅 영향 없음, ZCode 클라이언트 로그인 상태 사용)',
        'hint': '자격 증명은 ZCode 클라이언트 로그인으로 생성됩니다(~/.zcode/v2/config.json). 계정(OAuth) 로그인 시 암호화 저장되며, 이 경우 채팅은 ZCode 클라이언트 자체 로그인 상태를 사용하고 사용량 조회 등 보조 기능은 사용할 수 없습니다',
        'degraded': '평문 키 없음 · 클라이언트 로그인',
    },
}

for lang, t in APP.items():
    # app.json
    p = os.path.join(BASE, lang, 'app.json')
    d = json.load(open(p, encoding='utf-8'))
    banner = d['envBanner']
    banner.pop('browserHostTitle', None)   # 被 advisoryTitle 取代
    banner.pop('credentialsInvalid', None)  # 凭证不再进阻断档
    banner['advisoryTitle'] = t['advisoryTitle']
    banner['credsDegraded'] = t['credsDegraded']
    d['envErrors']['credsMissing'] = t['credsMissing']
    d['envErrors']['credsInvalid'] = t['credsInvalid']
    json.dump(d, open(p, 'w', encoding='utf-8'), ensure_ascii=False, indent=2)
    open(p, 'a', encoding='utf-8').write('\n')

    # settings.json
    p2 = os.path.join(BASE, lang, 'settings.json')
    d2 = json.load(open(p2, encoding='utf-8'))
    creds = d2['env']['credentials']
    creds.pop('invalid', None)
    creds['degraded'] = t['degraded']
    creds['hint'] = t['hint']
    json.dump(d2, open(p2, 'w', encoding='utf-8'), ensure_ascii=False, indent=2)
    open(p2, 'a', encoding='utf-8').write('\n')
    print(f'{lang}: app.json + settings.json updated')

print('done')
